version: '3.5'
services:
  php:
    build: './IaC/php/'
    volumes:
      - ./:/var/www/html/
    networks:
      - local
  apache:
    build: './IaC/apache/'
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    networks:
      - local
  mysql:
    build: './IaC/mysql/'
    ports: 
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=app
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --init-file="."
    networks:
      - local
volumes:
    db_data: {}
networks:
    local:
        driver: bridge